sources:
  - name: raw
    tables:
      - name: books
        columns:
          - Book-Author
          - Book-Title
          - ISBN
          - Image-URL-L
          - Image-URL-M
          - Image-URL-S
          - Publisher
          - Year-Of-Publication
      - name: users
        columns:
          - Age
          - Location
          - User-ID
      - name: ratings
        columns:
          - Book-Rating
          - ISBN
          - User-ID